/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectapp_perpustakaan;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author FAWKES
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MENU() {
        initComponents();
        setJam();
        //setExtendedState(MAXIMIZED_BOTH);
        DateFormat dateFormat = new SimpleDateFormat("dd-MMMM-yyyy");
        Calendar cal = Calendar.getInstance();
        labeltanggal.setText(dateFormat.format(cal.getTime()));
    }
    
    public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

            @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

labeljam.setText(jam+":"+menit+"");
}
};
new Timer(1000, taskPerformer).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labeljam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelmenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelbuku = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelpinjambuku = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelkembalibuku = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelclose = new javax.swing.JLabel();
        LabelDesktop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(132, 68, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        labeljam.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perpustakaan V.2");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        labeltanggal.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        labeltanggal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(labeljam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeltanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeljam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        labelmenu.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        labelmenu.setForeground(new java.awt.Color(255, 255, 255));
        labelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/anggota.png"))); // NOI18N
        labelmenu.setText("ANGGOTA");
        labelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelmenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelmenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        labelbuku.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        labelbuku.setForeground(new java.awt.Color(255, 255, 255));
        labelbuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/buku.png"))); // NOI18N
        labelbuku.setText("BUKU");
        labelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelbuku, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        labelpinjambuku.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        labelpinjambuku.setForeground(new java.awt.Color(255, 255, 255));
        labelpinjambuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpinjambuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pinjambuku.png"))); // NOI18N
        labelpinjambuku.setText("PINJAM BUKU");
        labelpinjambuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelpinjambukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelpinjambukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelpinjambukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelpinjambuku, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelpinjambuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        labelkembalibuku.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        labelkembalibuku.setForeground(new java.awt.Color(255, 255, 255));
        labelkembalibuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkembalibuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/kembalibuku.png"))); // NOI18N
        labelkembalibuku.setText("KEMBALI BUKU");
        labelkembalibuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkembalibukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelkembalibukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelkembalibukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkembalibuku, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkembalibuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        labelclose.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        labelclose.setForeground(new java.awt.Color(255, 255, 255));
        labelclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/close.png"))); // NOI18N
        labelclose.setText("Close");
        labelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelcloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelclose, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LabelDesktop.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        LabelDesktop.setForeground(new java.awt.Color(51, 51, 51));
        LabelDesktop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDesktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icon (1).gif"))); // NOI18N
        LabelDesktop.setText("PERPUSTAKAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void labelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_labelcloseMouseClicked

    private void labelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmenuMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        ANGGOTA OPEN = new ANGGOTA();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelmenuMouseClicked

    private void labelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbukuMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        BUKU OPEN = new BUKU();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelbukuMouseClicked

    private void labelpinjambukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelpinjambukuMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        PEMINJAMAN OPEN = new PEMINJAMAN();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelpinjambukuMouseClicked

    private void labelkembalibukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkembalibukuMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        KEMBALIKAN_BUKU OPEN = new KEMBALIKAN_BUKU();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelkembalibukuMouseClicked

    private void labelmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmenuMouseEntered
        // TODO add your handling code here:
        labelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grey3.png")));
        labelmenu.setForeground(Color.gray);
    }//GEN-LAST:event_labelmenuMouseEntered

    private void labelmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmenuMouseExited
        // TODO add your handling code here:
        labelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")));
        labelmenu.setForeground(Color.white);
    }//GEN-LAST:event_labelmenuMouseExited

    private void labelbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbukuMouseEntered
        // TODO add your handling code here:
        labelbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grey4.png")));
        labelbuku.setForeground(Color.gray);
    }//GEN-LAST:event_labelbukuMouseEntered

    private void labelbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbukuMouseExited
        // TODO add your handling code here:
        labelbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buku.png")));
        labelbuku.setForeground(Color.white);
    }//GEN-LAST:event_labelbukuMouseExited

    private void labelpinjambukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelpinjambukuMouseExited
        // TODO add your handling code here:
        labelpinjambuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pinjambuku.png")));
        labelpinjambuku.setForeground(Color.white);
    }//GEN-LAST:event_labelpinjambukuMouseExited

    private void labelpinjambukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelpinjambukuMouseEntered
        // TODO add your handling code here:
        labelpinjambuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grey5.png")));
        labelpinjambuku.setForeground(Color.gray);
    }//GEN-LAST:event_labelpinjambukuMouseEntered

    private void labelkembalibukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkembalibukuMouseExited
        // TODO add your handling code here:
        labelkembalibuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kembalibuku.png")));
        labelkembalibuku.setForeground(Color.white);
    }//GEN-LAST:event_labelkembalibukuMouseExited

    private void labelkembalibukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkembalibukuMouseEntered
        // TODO add your handling code here:
        labelkembalibuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grey2.png")));
        labelkembalibuku.setForeground(Color.gray);
    }//GEN-LAST:event_labelkembalibukuMouseEntered

    private void labelcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcloseMouseExited
        // TODO add your handling code here:
        labelclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png")));
        labelclose.setForeground(Color.white);
    }//GEN-LAST:event_labelcloseMouseExited

    private void labelcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcloseMouseEntered
        // TODO add your handling code here:
        labelclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grey1.png")));
        labelclose.setForeground(Color.gray);
    }//GEN-LAST:event_labelcloseMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelbuku;
    private javax.swing.JLabel labelclose;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labelkembalibuku;
    private javax.swing.JLabel labelmenu;
    private javax.swing.JLabel labelpinjambuku;
    private javax.swing.JLabel labeltanggal;
    // End of variables declaration//GEN-END:variables
}
